// Fuente de verdad de los features de cada plan

const PLANS = {
  BASICO: "basico",
  PRO: "pro",
};

const PLAN_FEATURES = {
  basico: [
    // Módulos permitidos para plan básico
    "articulos",
    "inventario",
    "ventas",
    "compras",
    "seguimiento_inventario",
    "clientes",
    "proveedores",
    "usuarios",
    "roles",
    "categorias",
    "unidades",
    "trabajadores",
    "dashboard",
    "tesoreria",
    "reportes",
    "devoluciones",
  ],
  básico: [
    // Módulos permitidos para plan básico (nombre con tilde)
    "articulos",
    "inventario",
    "ventas",
    "compras",
    "seguimiento_inventario",
    "clientes",
    "proveedores",
    "usuarios",
    "roles",
    "categorias",
    "unidades",
    "trabajadores",
    "dashboard",
    "tesoreria",
    "reportes",
    "devoluciones",
  ],
  pro: [
    // Acceso total a todos los módulos
    "articulos",
    "dashboard",
    "inventario",
    "seguimiento_inventario",
    "movimientos_inventario",
    "compras",
    "ventas",
    "reportes",
    "categorias",
    "proveedores",
    "clientes",
    "unidades",
    "usuarios",
    "roles",
    "fabricacion",
    "kanban",
    "progreso",
    "tesoreria",
    "costos",
    "trabajadores",
    "pagos",
    "anticipos",
    "creditos",
    "cierres_caja",
    "costos_materia_prima",
    "lotes",
    "etapas",
    "avances",
    "ordenes",
    "ordenes_pedido",
    "devoluciones",
  ],
  pro: [
    // Acceso total a todos los módulos
    "articulos",
    "dashboard",
    "inventario",
    "seguimiento_inventario",
    "movimientos_inventario",
    "compras",
    "ventas",
    "reportes",
    "categorias",
    "proveedores",
    "clientes",
    "unidades",
    "usuarios",
    "roles",
    "fabricacion",
    "kanban",
    "progreso",
    "tesoreria",
    "costos",
    "trabajadores",
    "pagos",
    "anticipos",
    "creditos",
    "cierres_caja",
    "costos_materia_prima",
    "lotes",
    "etapas",
    "avances",
    "ordenes",
    "ordenes_pedido",
    "devoluciones",
  ],
};

module.exports = { PLANS, PLAN_FEATURES };
